name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up build environment
        run: sudo apt update && sudo apt install -y gcc make
      
      - name: Build project
        run: make all
      
      - name: Verify binary
        run: test -f build/cnetlab